name: 'S3 & CloudFront Deploy'

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  cloudfront_deployment:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      NEXT_PUBLIC_KAKAO_JAVASCRIPT_KEY: ${{ secrets.KAKAO_JAVASCRIPT_KEY }}
      NEXT_PUBLIC_KAKAO_REDIRECT_URL: ${{ secrets.KAKAO_REDIRECT_URL_DEVELOPMENT }}
      BASE_REQUEST_URL: ${{ secrets.BASE_REQUEST_URL_DEVELOPMENT }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn

      - name: Build and export next app
        run: |
          NEXT_PUBLIC_KAKAO_JAVASCRIPT_KEY=$NEXT_PUBLIC_KAKAO_JAVASCRIPT_KEY
          NEXT_PUBLIC_KAKAO_REDIRECT_URL=$NEXT_PUBLIC_KAKAO_REDIRECT_URL
          BASE_REQUEST_URL=$BASE_REQUEST_URL
          REWRITE_URL='http://rewrites.com'
          yarn build

      - name: Deploy CloudFront
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: out
          bucket: ${{ secrets.S3_BUCKET }}
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: / *
